import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`DROP INDEX \`contact_us_email_idx\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`is_site_content\` integer DEFAULT false;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`header_title\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`location_title\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`address\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`see_map_link\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`email_title\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`email_address\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`email_link\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`phone_title\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`phone_numbers\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`phone_link\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`active\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`published_at\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`name\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`email\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`subject\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`message\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`phone\`;`)
  await db.run(sql`ALTER TABLE \`users\` ADD \`active\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`active\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`published_at\` text;`)
  await db.run(sql`ALTER TABLE \`features\` ADD \`published_at\` text;`)
  await db.run(sql`ALTER TABLE \`footer\` ADD \`active\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`footer\` ADD \`published_at\` text;`)
  await db.run(sql`ALTER TABLE \`hero\` ADD \`published_at\` text;`)
  await db.run(sql`ALTER TABLE \`_hero_v\` ADD \`version_published_at\` text;`)
  await db.run(sql`ALTER TABLE \`nav_items\` ADD \`active\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`nav_items\` ADD \`published_at\` text;`)
  await db.run(sql`ALTER TABLE \`what_we_do\` ADD \`description\` text;`)
  await db.run(sql`ALTER TABLE \`what_we_do\` ADD \`label\` text;`)
  await db.run(sql`ALTER TABLE \`what_we_do\` ADD \`cta\` text;`)
  await db.run(sql`ALTER TABLE \`what_we_do\` ADD \`video_url\` text;`)
  await db.run(sql`ALTER TABLE \`what_we_do\` ADD \`published_at\` text;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`name\` text NOT NULL;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`email\` text NOT NULL;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`subject\` text;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`message\` text NOT NULL;`)
  await db.run(sql`ALTER TABLE \`contact_us\` ADD \`phone\` text;`)
  await db.run(sql`CREATE INDEX \`contact_us_email_idx\` ON \`contact_us\` (\`email\`);`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`is_site_content\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`header_title\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`location_title\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`address\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`see_map_link\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`email_title\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`email_address\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`email_link\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`phone_title\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`phone_numbers\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`phone_link\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`active\`;`)
  await db.run(sql`ALTER TABLE \`contact_us\` DROP COLUMN \`published_at\`;`)
  await db.run(sql`ALTER TABLE \`users\` DROP COLUMN \`active\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`active\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`published_at\`;`)
  await db.run(sql`ALTER TABLE \`features\` DROP COLUMN \`published_at\`;`)
  await db.run(sql`ALTER TABLE \`footer\` DROP COLUMN \`active\`;`)
  await db.run(sql`ALTER TABLE \`footer\` DROP COLUMN \`published_at\`;`)
  await db.run(sql`ALTER TABLE \`hero\` DROP COLUMN \`published_at\`;`)
  await db.run(sql`ALTER TABLE \`_hero_v\` DROP COLUMN \`version_published_at\`;`)
  await db.run(sql`ALTER TABLE \`nav_items\` DROP COLUMN \`active\`;`)
  await db.run(sql`ALTER TABLE \`nav_items\` DROP COLUMN \`published_at\`;`)
  await db.run(sql`ALTER TABLE \`what_we_do\` DROP COLUMN \`description\`;`)
  await db.run(sql`ALTER TABLE \`what_we_do\` DROP COLUMN \`label\`;`)
  await db.run(sql`ALTER TABLE \`what_we_do\` DROP COLUMN \`cta\`;`)
  await db.run(sql`ALTER TABLE \`what_we_do\` DROP COLUMN \`video_url\`;`)
  await db.run(sql`ALTER TABLE \`what_we_do\` DROP COLUMN \`published_at\`;`)
}
