/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'contact-us': ContactUs;
    'contact-submissions': ContactSubmission;
    features: Feature;
    footer: Footer;
    hero: Hero;
    'nav-items': NavItem;
    'what-we-do': WhatWeDo;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-us': ContactUsSelect<false> | ContactUsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'nav-items': NavItemsSelect<false> | NavItemsSelect<true>;
    'what-we-do': WhatWeDoSelect<false> | WhatWeDoSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admin users can create, edit, and delete content
   */
  roles: 'admin'[];
  /**
   * Whether this user account is active
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility
   */
  alt: string;
  /**
   * Whether this media item is visible/public
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Site-managed contact page content (separate from user submissions)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us".
 */
export interface ContactUs {
  id: number;
  /**
   * Set to true for the site-managed contact info (admin only)
   */
  isSiteContent?: boolean | null;
  /**
   * Main header title for the contact page
   */
  headerTitle?: string | null;
  /**
   * Header subtitle/paragraph
   */
  headerSubtitle?: string | null;
  /**
   * Location card title (e.g., Drop us a line)
   */
  locationTitle?: string | null;
  /**
   * Address HTML/text for the location card
   */
  address?: string | null;
  /**
   * URL for See Map link
   */
  seeMapLink?: string | null;
  /**
   * Email card title (e.g., Email)
   */
  emailTitle?: string | null;
  /**
   * Public contact email address
   */
  emailAddress?: string | null;
  /**
   * mailto: link or other URL for the email card
   */
  emailLink?: string | null;
  /**
   * Phone card title (e.g., Call)
   */
  phoneTitle?: string | null;
  /**
   * Phone numbers text (can include line breaks)
   */
  phoneNumbers?: string | null;
  /**
   * tel: link or other URL for phone action
   */
  phoneLink?: string | null;
  /**
   * Whether this submission is active/visible in the admin list
   */
  active?: boolean | null;
  /**
   * Optional publication date/time or handled time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public contact form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  /**
   * Contact person name
   */
  name: string;
  /**
   * Contact email address
   */
  email: string;
  /**
   * Message subject
   */
  subject?: string | null;
  /**
   * Message content
   */
  message: string;
  /**
   * Optional contact phone number
   */
  phone?: string | null;
  /**
   * Whether the submission is active
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage feature items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  /**
   * Feature title
   */
  title: string;
  /**
   * Feature description
   */
  description?: string | null;
  /**
   * Icon class or identifier
   */
  icon?: string | null;
  /**
   * Feature image
   */
  image?: (number | null) | Media;
  /**
   * Display order
   */
  order?: number | null;
  /**
   * Whether this feature is visible
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage footer sections and links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Footer sections with links
   */
  sections?:
    | {
        /**
         * Section label/title
         */
        label?: string | null;
        /**
         * Links in this section
         */
        links?:
          | {
              /**
               * Link text
               */
              label?: string | null;
              /**
               * Link URL
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright message (e.g., "Made with love for great people.")
   */
  copyrightMessage?: string | null;
  /**
   * Copyright text (e.g., "© Copyright 2024 - JCAR LLC dba Premier...")
   */
  copyrightYear?: string | null;
  /**
   * Whether this footer is active/public
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage hero section content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * Main hero headline
   */
  headline: string;
  /**
   * Subheading text
   */
  subheadline?: string | null;
  /**
   * Call-to-action button text
   */
  ctaText?: string | null;
  /**
   * Call-to-action button URL
   */
  ctaUrl?: string | null;
  /**
   * Hero background image
   */
  background?: (number | null) | Media;
  /**
   * Whether this hero section is visible (only one active at a time)
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage navigation menu items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-items".
 */
export interface NavItem {
  id: number;
  /**
   * Menu item text
   */
  label: string;
  /**
   * Menu item link URL
   */
  url: string;
  /**
   * Display order in menu
   */
  order?: number | null;
  /**
   * Whether this menu item is visible
   */
  visible?: boolean | null;
  /**
   * Whether this link opens in a new tab
   */
  external?: boolean | null;
  /**
   * Whether this nav item is active (preferred over visible)
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage "What We Do" section items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "what-we-do".
 */
export interface WhatWeDo {
  id: number;
  /**
   * Item title
   */
  title: string;
  /**
   * Item subtitle
   */
  subtitle?: string | null;
  /**
   * Item description (also used as main section description if present on first item)
   */
  description?: string | null;
  /**
   * Item image
   */
  image?: (number | null) | Media;
  /**
   * Display order
   */
  order?: number | null;
  /**
   * Whether this item is visible
   */
  active?: boolean | null;
  /**
   * Main section title (used only on first item)
   */
  mainTitle?: string | null;
  /**
   * Small label shown above the main title (e.g., ONE-STOP SOLUTION)
   */
  label?: string | null;
  /**
   * Call-to-action text for the main section
   */
  cta?: string | null;
  /**
   * Optional video embed URL (e.g., https://www.youtube.com/embed/...)
   */
  videoUrl?: string | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-us';
        value: number | ContactUs;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'footer';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'hero';
        value: number | Hero;
      } | null)
    | ({
        relationTo: 'nav-items';
        value: number | NavItem;
      } | null)
    | ({
        relationTo: 'what-we-do';
        value: number | WhatWeDo;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us_select".
 */
export interface ContactUsSelect<T extends boolean = true> {
  isSiteContent?: T;
  headerTitle?: T;
  headerSubtitle?: T;
  locationTitle?: T;
  address?: T;
  seeMapLink?: T;
  emailTitle?: T;
  emailAddress?: T;
  emailLink?: T;
  phoneTitle?: T;
  phoneNumbers?: T;
  phoneLink?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  phone?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  image?: T;
  order?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightMessage?: T;
  copyrightYear?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  headline?: T;
  subheadline?: T;
  ctaText?: T;
  ctaUrl?: T;
  background?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-items_select".
 */
export interface NavItemsSelect<T extends boolean = true> {
  label?: T;
  url?: T;
  order?: T;
  visible?: T;
  external?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "what-we-do_select".
 */
export interface WhatWeDoSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  image?: T;
  order?: T;
  active?: T;
  mainTitle?: T;
  label?: T;
  cta?: T;
  videoUrl?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}