/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'contact-us-content': ContactUsContent;
    'contact-submissions-form': ContactSubmissionsForm;
    'features-final': FeaturesFinal;
    'footer-final': FooterFinal;
    'hero-final': HeroFinal;
    'navbar-final': NavbarFinal;
    'what-wedo-final': WhatWedoFinal;
    'services-final': ServicesFinal;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-us-content': ContactUsContentSelect<false> | ContactUsContentSelect<true>;
    'contact-submissions-form': ContactSubmissionsFormSelect<false> | ContactSubmissionsFormSelect<true>;
    'features-final': FeaturesFinalSelect<false> | FeaturesFinalSelect<true>;
    'footer-final': FooterFinalSelect<false> | FooterFinalSelect<true>;
    'hero-final': HeroFinalSelect<false> | HeroFinalSelect<true>;
    'navbar-final': NavbarFinalSelect<false> | NavbarFinalSelect<true>;
    'what-wedo-final': WhatWedoFinalSelect<false> | WhatWedoFinalSelect<true>;
    'services-final': ServicesFinalSelect<false> | ServicesFinalSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admin users can create, edit, and delete content
   */
  roles: 'admin'[];
  /**
   * Whether this user account is active
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility
   */
  alt: string;
  /**
   * Whether this media item is visible/public
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Site-managed contact page content (separate from user submissions)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us-content".
 */
export interface ContactUsContent {
  id: number;
  /**
   * Set to true for the site-managed contact info (admin only)
   */
  isSiteContent?: boolean | null;
  /**
   * Main header title for the contact page
   */
  headerTitle?: string | null;
  /**
   * Header subtitle/paragraph
   */
  headerSubtitle?: string | null;
  /**
   * Location card title (e.g., Drop us a line)
   */
  locationTitle?: string | null;
  /**
   * Address HTML/text for the location card. Use <br/> or newlines to separate lines; frontend splits on <br/> or
   * .
   */
  address?: string | null;
  /**
   * Structured address lines (preferred). Each entry is a single line; frontend will render each on its own line.
   */
  addressLines?:
    | {
        /**
         * One address line
         */
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL for See Map link
   */
  seeMapLink?: string | null;
  /**
   * Email card title (e.g., Email)
   */
  emailTitle?: string | null;
  /**
   * Public contact email address
   */
  emailAddress?: string | null;
  /**
   * mailto: link or other URL for the email card
   */
  emailLink?: string | null;
  /**
   * Phone card title (e.g., Call)
   */
  phoneTitle?: string | null;
  /**
   * Phone numbers text (can include multiple numbers separated by <br/> or newlines). Frontend splits on <br/> or
   * .
   */
  phoneNumbers?: string | null;
  /**
   * Structured phone numbers (preferred). Each entry can have a label and a number.
   */
  phoneList?:
    | {
        /**
         * Optional label for the phone number (e.g., Local, Toll Free)
         */
        label?: string | null;
        /**
         * Phone number string (displayed as-is)
         */
        number?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * tel: link or other URL for phone action
   */
  phoneLink?: string | null;
  /**
   * Whether this submission is active/visible in the admin list
   */
  active?: boolean | null;
  /**
   * Optional publication date/time or handled time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public contact form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions-form".
 */
export interface ContactSubmissionsForm {
  id: number;
  /**
   * Contact person name
   */
  name: string;
  /**
   * Contact email address
   */
  email: string;
  /**
   * Message subject
   */
  subject?: string | null;
  /**
   * Message content
   */
  message: string;
  /**
   * Optional contact phone number
   */
  phone?: string | null;
  /**
   * Whether the submission is active
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage feature items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features-final".
 */
export interface FeaturesFinal {
  id: number;
  /**
   * Main section header title (e.g., Everything in One Place)
   */
  mainTitle?: string | null;
  /**
   * Main section header subtitle (e.g., We go further than all of our competitors.)
   */
  mainSubtitle?: string | null;
  /**
   * Feature title
   */
  title: string;
  /**
   * Feature subtitle (renders under title)
   */
  subtitle?: string | null;
  /**
   * Feature description
   */
  description?: string | null;
  /**
   * Feature image
   */
  image?: (number | null) | Media;
  /**
   * Display order
   */
  order?: number | null;
  /**
   * Whether this feature is visible
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage footer sections and links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-final".
 */
export interface FooterFinal {
  id: number;
  /**
   * Footer sections with links
   */
  sections?:
    | {
        /**
         * Section label/title
         */
        label?: string | null;
        /**
         * Links in this section
         */
        links?:
          | {
              /**
               * Link text
               */
              label?: string | null;
              /**
               * Link URL
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright message (e.g., "Made with love for great people.")
   */
  copyrightMessage?: string | null;
  /**
   * Title lines displayed in the footer CTA (eg:-Ready to get started with). Each entry is a single line.
   */
  titleLines?:
    | {
        /**
         * One title line
         */
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Just like(Premier?).
   */
  titleSpans?:
    | {
        /**
         * Span text
         */
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * CTA button text displayed in the footer (e.g., Get a Consultation)
   */
  ctaButtonText?: string | null;
  /**
   * CTA button URL (optional)
   */
  ctaButtonUrl?: string | null;
  /**
   * Copyright text (e.g., "© Copyright 2024 - JCAR LLC dba Premier...")
   */
  copyrightYear?: string | null;
  /**
   * Whether this footer is active/public
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage hero section content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-final".
 */
export interface HeroFinal {
  id: number;
  /**
   * Main headline's premier part (e.g. 'Premier')
   */
  titlePremier: string;
  /**
   * Subtitle lines (one per row) e.g. Document / Imaging / Solutions
   */
  subtitleLines?:
    | {
        /**
         * One subtitle line
         */
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Supporting subtext under the title
   */
  subtext?: string | null;
  /**
   * Call-to-action button text
   */
  ctaText?: string | null;
  /**
   * Call-to-action button URL/link
   */
  ctaUrl?: string | null;
  /**
   * Hero image (used as imageSrc in frontend)
   */
  image?: (number | null) | Media;
  /**
   * Whether this hero section is visible (only one active at a time)
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage navigation menu items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar-final".
 */
export interface NavbarFinal {
  id: number;
  /**
   * Menu item text
   */
  label: string;
  /**
   * Menu item link URL
   */
  url: string;
  /**
   * Display order in menu
   */
  order?: number | null;
  /**
   * Whether this menu item is visible
   */
  visible?: boolean | null;
  /**
   * Mark this document as site settings (store logoText/logoImage here). Only one settings doc is recommended.
   */
  isSiteSettings?: boolean | null;
  /**
   * Optional site logo text used when this document is marked as site settings
   */
  logoText?: string | null;
  /**
   * Optional site logo image used when this document is marked as site settings
   */
  logoImage?: (number | null) | Media;
  /**
   * Whether this link opens in a new tab
   */
  external?: boolean | null;
  /**
   * Display as a button instead of a link (e.g., Free Trial)
   */
  isButton?: boolean | null;
  /**
   * Whether this nav item is active (preferred over visible)
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage "What We Do" section items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "what-wedo-final".
 */
export interface WhatWedoFinal {
  id: number;
  /**
   * Small label shown above the main title (e.g., ONE-STOP SOLUTION)
   */
  label?: string | null;
  /**
   * Main section title (e.g., What we do)
   */
  title?: string | null;
  /**
   * Main description text
   */
  description?: string | null;
  /**
   * Call-to-action text (e.g., Call us for a guided demonstration)
   */
  cta?: string | null;
  /**
   * YouTube embed URL (e.g., https://www.youtube.com/embed/A0hbkovu_F8)
   */
  videoUrl?: string | null;
  /**
   * Button text (e.g., Check out our live demo site)
   */
  buttonText?: string | null;
  /**
   * Button URL/link
   */
  buttonUrl?: string | null;
  /**
   * Whether this section is active/visible
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage service offerings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-final".
 */
export interface ServicesFinal {
  id: number;
  /**
   * Service title
   */
  title: string;
  /**
   * Service subtitle
   */
  subtitle: string;
  /**
   * Service icon image
   */
  icon: number | Media;
  /**
   * Display order
   */
  order?: number | null;
  /**
   * Whether this service is visible
   */
  active?: boolean | null;
  /**
   * Optional publication date/time
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-us-content';
        value: number | ContactUsContent;
      } | null)
    | ({
        relationTo: 'contact-submissions-form';
        value: number | ContactSubmissionsForm;
      } | null)
    | ({
        relationTo: 'features-final';
        value: number | FeaturesFinal;
      } | null)
    | ({
        relationTo: 'footer-final';
        value: number | FooterFinal;
      } | null)
    | ({
        relationTo: 'hero-final';
        value: number | HeroFinal;
      } | null)
    | ({
        relationTo: 'navbar-final';
        value: number | NavbarFinal;
      } | null)
    | ({
        relationTo: 'what-wedo-final';
        value: number | WhatWedoFinal;
      } | null)
    | ({
        relationTo: 'services-final';
        value: number | ServicesFinal;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us-content_select".
 */
export interface ContactUsContentSelect<T extends boolean = true> {
  isSiteContent?: T;
  headerTitle?: T;
  headerSubtitle?: T;
  locationTitle?: T;
  address?: T;
  addressLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  seeMapLink?: T;
  emailTitle?: T;
  emailAddress?: T;
  emailLink?: T;
  phoneTitle?: T;
  phoneNumbers?: T;
  phoneList?:
    | T
    | {
        label?: T;
        number?: T;
        id?: T;
      };
  phoneLink?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions-form_select".
 */
export interface ContactSubmissionsFormSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  phone?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features-final_select".
 */
export interface FeaturesFinalSelect<T extends boolean = true> {
  mainTitle?: T;
  mainSubtitle?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  image?: T;
  order?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-final_select".
 */
export interface FooterFinalSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightMessage?: T;
  titleLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  titleSpans?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ctaButtonText?: T;
  ctaButtonUrl?: T;
  copyrightYear?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-final_select".
 */
export interface HeroFinalSelect<T extends boolean = true> {
  titlePremier?: T;
  subtitleLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  subtext?: T;
  ctaText?: T;
  ctaUrl?: T;
  image?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar-final_select".
 */
export interface NavbarFinalSelect<T extends boolean = true> {
  label?: T;
  url?: T;
  order?: T;
  visible?: T;
  isSiteSettings?: T;
  logoText?: T;
  logoImage?: T;
  external?: T;
  isButton?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "what-wedo-final_select".
 */
export interface WhatWedoFinalSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  description?: T;
  cta?: T;
  videoUrl?: T;
  buttonText?: T;
  buttonUrl?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-final_select".
 */
export interface ServicesFinalSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  icon?: T;
  order?: T;
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}